### ISSUE TITLE
for式のfilterに関する記述

### ISSUE THREAD

**Issue by xuwei-k** [hatena/Hatena-Textbook#16]
https://github.com/hatena/Hatena-Textbook/blob/71680f6d034f8a904e075adecf16faff79ffc653/foundation-of-programming-scala.md#ガードつきのfor

> filter メソッドが実装されてるとifでfilterできる

という箇所、withFilterについて書いてない。そもそもテキストのScalaのversionの指定がない(?)ので、どう修正すべきかは、どのScalaのversionをサポートするのか？によるが

- 古いversionもケアするなら、filterとwithFilter両方に関して(歴史的なこと含め)説明をかく
- 最新versionのScalaだけでいいなら、上記のfilterの記述をwithFilterに単に置き換えるべき

**Comment by xuwei-k** [comment]
> そもそもテキストのScalaのversionの指定がない

```scala
scalaVersion := "2.11.7"
```

という記述はあるか

**Comment by hakobe** [comment]
https://github.com/hatena/Hatena-Textbook/issues/18 こちらで記載を追加するなどしました。ご指摘ありがとうございました!!
