### ISSUE TITLE
Scalaスケーラブルプログラミング (コップ本) は第3版出てる

### ISSUE THREAD

**Issue by xuwei-k** [hatena/Hatena-Textbook#24]
https://github.com/hatena/Hatena-Textbook/blob/512f11b661c403fe5ef290c67df4e0948a89db2c/foundation-of-programming-scala.md#書籍

**Comment by daiksy** [comment]
ご指摘ありがとうございます！！！！！

**Comment by daiksy** [comment]
修正しました。
